[package]
name = "moonlight-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
moonlight-dsp = { path = "../moonlight-dsp" }
moonlight-model = { path = "../moonlight-model" }

[[bin]]
name = "moonlight-bench"
path = "src/main.rs"
